### ISSUE TITLE
joelanman July 12 2015 at 09:53PM

### ISSUE THREAD

**Issue by ChelseaStats** [ChelseaStats/issues#454]
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr" xml:lang="en">3D diagrams of underground stations <a href="http://u.thechels.uk/1Rs8gpC">http://u.thechels.uk/1Rs8gpC</a> <a href="http://u.thechels.uk/1HyYh77">http://pic.twitter.com/5g8bzl8Of5</a></p>
&mdash; Joe Lanman (@ joelanman) <a href="https://twitter.com/joelanman/status/620335133325922304">July 12, 2015</a>
</blockquote>

<br><br>
July 12, 2015 at 09:53PM<br>
via Twitter<br><hr><br><br>
http://twitter.com/joelanman/status/620335133325922304

**Comment by joelanman** [comment]
What is this?

**Comment by ChelseaStats** [comment]
sorry, my workflow for interesting things on twitter is to log a github issue (using IFTTT). Looks like it tagged you here, i'll edit to remove. 

Sorry about that.
